-- 기존 객체가 있으면 필요에 따라 먼저 삭제합니다.
-- DROP TABLE CHICKEN_STORE;
-- DROP SEQUENCE SEQ_CHICKEN_STORE;

CREATE TABLE TBL_CHICKEN_STORE
(
    STORE_NO        NUMBER          PRIMARY KEY,
    BRAND_NAME      VARCHAR2(30)    NOT NULL,
    STORE_NAME      VARCHAR2(120)   NOT NULL,
    PHONE           VARCHAR2(40),
    RAW_ADDRESS     VARCHAR2(400),
    CLEAN_ADDRESS   VARCHAR2(400),
    SIDO            VARCHAR2(50),
    SIGUNGU         VARCHAR2(80),
    LATITUDE        NUMBER(10, 7),
    LONGITUDE       NUMBER(10, 7),
    GEOCODE_STATUS  VARCHAR2(20),
    COLLECTED_AT    DATE,
    CREATED_AT      DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_CHICKEN_STORE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 생성 확인
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME = 'CHICKEN_STORE';

SELECT SEQUENCE_NAME
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'SEQ_CHICKEN_STORE';
