-- 전체 데이터 수
SELECT COUNT(*) AS TOTAL_COUNT
FROM CHICKEN_STORE;

-- 브랜드별 매장 수
SELECT BRAND_NAME,
       COUNT(*) AS STORE_COUNT
FROM CHICKEN_STORE
GROUP BY BRAND_NAME
ORDER BY STORE_COUNT DESC;

-- 지역별 매장 수
SELECT SIDO,
       COUNT(*) AS STORE_COUNT
FROM CHICKEN_STORE
GROUP BY SIDO
ORDER BY STORE_COUNT DESC;

-- 좌표 변환 성공 데이터
SELECT STORE_NO,
       BRAND_NAME,
       STORE_NAME,
       CLEAN_ADDRESS,
       LATITUDE,
       LONGITUDE
FROM CHICKEN_STORE
WHERE GEOCODE_STATUS = 'SUCCESS'
ORDER BY STORE_NO;

-- 좌표 변환 실패 데이터
SELECT STORE_NO,
       BRAND_NAME,
       STORE_NAME,
       CLEAN_ADDRESS
FROM CHICKEN_STORE
WHERE GEOCODE_STATUS = 'FAILED'
   OR LATITUDE IS NULL
   OR LONGITUDE IS NULL;
